/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alzhimerdetectionsystem;


import AlzhimerDetection.Super_Pixel;
import static AlzhimerDetection.Super_Pixel.loadImage;
import static AlzhimerDetection.Super_Pixel.saveImage;
import ConvNuralNetwork.Convolution.POJO.JAVABeans;
import alzhimerdetectionsystem.KNN.FeatureVectorComparision;
import graph.BarChart1;
import graph.barchart;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.highgui.Highgui;
import org.opencv.photo.Photo;

/**
 *
 * @author Codeft
 */
public class MainUI extends javax.swing.JFrame {
String selectedImagePath = "";
    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 700));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("BROWSE");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 70, 140, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("i/p image path ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 70, 86, 20);

        jTextField1.setText("  ");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(380, 60, 490, 30);

        jLabel2.setText(" ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 110, 140, 180);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("i/p image");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 150, 90, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("L0SMOOTHING");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 110, 140, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("SUPER PIXEL");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(740, 110, 130, 30);

        jLabel4.setText(" ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 150, 140, 180);

        jLabel5.setText(" ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(740, 150, 130, 180);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setText("SIFT");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(60, 350, 100, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setText("CNN");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(260, 350, 100, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton6.setText("LBP");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(440, 350, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Feature vector");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(250, 400, 140, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 440, 550, 190);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton7.setText("KNN");
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(690, 350, 100, 30);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(660, 440, 190, 190);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 204));
        jLabel7.setText("Alzhimer Detection");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(360, 0, 230, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Result");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(710, 400, 90, 20);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton8.setText(" Featurevector Graph");
        jButton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(930, 350, 170, 30);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton9.setText("Dataset graph");
        jButton9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(1140, 350, 110, 30);

        jButton10.setText("BROWSE TEST FOLDER");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(920, 60, 150, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser Browse=new JFileChooser();
        int showOpenDialog=Browse.showOpenDialog(jTextField1);
        FileNameExtensionFilter fnet=new FileNameExtensionFilter("Image", "png","jpg");
        Browse.addChoosableFileFilter(fnet);
        if(showOpenDialog == JFileChooser.APPROVE_OPTION)
        {
            File selectedImageFile=Browse.getSelectedFile();
            selectedImagePath= selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, selectedImagePath);
            
             //Diaplay image
            ImageIcon ii = new ImageIcon(selectedImagePath);
            Image imFit=ii.getImage();
            Image imgFit=imFit.getScaledInstance(jLabel2.getWidth(),jLabel2.getHeight(),Image.SCALE_SMOOTH);
            
            jLabel2.setIcon(new  ImageIcon(imgFit));
            jLabel3.getText();
            jTextField1.setText(selectedImagePath);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           String Path = jTextField1.getText();
       
         System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        System.out.println("liabrary Added Succesufully.");
       
       Mat input = Highgui.imread(selectedImagePath, Highgui.IMREAD_GRAYSCALE);
       
        // Apply L0 smoothing
        Mat output = new Mat();
        Photo.fastNlMeansDenoising(input, output, 0.05f, 1, 11);
       
        // Save output image
        Highgui.imwrite(selectedImagePath, output);
        // saveImage(Mat);
          ImageIcon ii = new ImageIcon(Path);
          Image imFit=ii.getImage();
            Image imgFit=imFit.getScaledInstance(jLabel4.getWidth(),jLabel4.getHeight(),Image.SCALE_SMOOTH);
           
            jLabel4.setIcon(new ImageIcon(imgFit));
       
       
            jLabel4.setText(Path);
                                
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public Image LoSmoothing(String Path)
    {
    
         System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        System.out.println("liabrary Added Succesufully.");
       
       Mat input = Highgui.imread(Path, Highgui.IMREAD_GRAYSCALE);
       
        // Apply L0 smoothing
        Mat output = new Mat();
        Photo.fastNlMeansDenoising(input, output, 0.05f, 1, 11);
       
        // Save output image
        Highgui.imwrite("smooth.png", output);
        // saveImage(Mat);
          ImageIcon ii = new ImageIcon(Path );
          Image imFit=ii.getImage();
            Image imgFit=imFit.getScaledInstance(jLabel4.getWidth(),jLabel4.getHeight(),Image.SCALE_SMOOTH);
       
    return imFit;
    
    
    }
    
    
    public  void SuperPixel(String path)
    {
   // String src = jTextField1.getText();
        //String src = "E://birds.png";
        //String dst = args[1];
        String dst = "D:\\Alzaimer\\segment.png";
       
        double S =50;
       
        double m = 130.0;
       
        BufferedImage img = loadImage(path);
        Super_Pixel sp = new Super_Pixel();
        BufferedImage dstImage = sp.calculate(img,S,m);
        // save the resulting image
        sp.saveImage(dst, dstImage);
          ImageIcon ii = new ImageIcon(dst);
        Image imFit=ii.getImage();
            Image imgFit=imFit.getScaledInstance(jLabel5.getWidth(),jLabel5.getHeight(),Image.SCALE_SMOOTH);
         
    }
    
    
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         String src = jTextField1.getText();
        //String src = "E://birds.png";
        //String dst = args[1];
          String dst = "D:\\Alzaimer\\segment.png";
       
        double S =50;
       
        double m = 130.0;
       
        BufferedImage img = loadImage(src);
        Super_Pixel sp = new Super_Pixel();
        BufferedImage dstImage = sp.calculate(img,S,m);
        // save the resulting image
        saveImage(dst, dstImage);
          ImageIcon ii = new ImageIcon(dst);
        Image imFit=ii.getImage();
            Image imgFit=imFit.getScaledInstance(jLabel5.getWidth(),jLabel5.getHeight(),Image.SCALE_SMOOTH);
           
            jLabel5.setIcon(new  ImageIcon(imgFit));
       
       
        jLabel5.setText(src);
                                 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          try {
            AlzhimerDetectionSystem.main(selectedImagePath,"train");
        } catch (IOException ex) {
           
        }
        
          
         ArrayList<String> SIFTFeatures = JAVABeans.getSIFTFeatures();
            for (int i = 0; i < SIFTFeatures.size(); i++) {
            String get = SIFTFeatures.get(i);
            jTextArea1.append(get);
            jTextArea1.append("\n");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    Vector<Integer> CNNFeatures = JAVABeans.getCNNFeatures();
        for (int i = 0; i < CNNFeatures.size(); i++) {
            Integer elementAt = CNNFeatures.elementAt(i);
            jTextArea1.append(""+elementAt);
            jTextArea1.append("\n");
        }
     
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       int[] LBPFeatures = JAVABeans.getLBPFeatures();
        for (int i = 0; i < LBPFeatures.length; i++) {
            int LBPFeature = LBPFeatures[i];
            jTextArea1.append(""+LBPFeature);
            jTextArea1.append("\n");
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       ArrayList<String> Result = FeatureVectorComparision.main(null);
         for (int i = 0; i < Result.size(); i++) {
            String get = Result.get(i);
            jTextArea2.append(get);
            jTextArea2.append("\n");
            
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

       BarChart1 example=new BarChart1("Bar Chart Window");  
      example.setSize(800, 400);  
      example.setLocationRelativeTo(null);  
      example.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);  
      example.setVisible(true);  
   
        
 
       
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
     
    
      barchart example=new   barchart("Bar Chart Window");  
      example.setSize(800, 400);  
      example.setLocationRelativeTo(null);  
      example.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);  
      example.setVisible(true);  
   
      
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

         JFileChooser fileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

        // Set the file chooser to select directories only
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        // Show the file chooser dialog
        int returnValue = fileChooser.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File folder = fileChooser.getSelectedFile();

            // Check if the selected path is a directory
            if (folder.isDirectory()) {
                // Get all files in the selected folder
                File[] files = folder.listFiles();

                // Iterate through each file in the folder
                if (files != null) {
                    for (File file : files) {
                        if (file.isFile()) {
                            String filePath = file.getAbsolutePath();
                            System.out.println(filePath);
                           try{
        LoSmoothing(filePath);
        SuperPixel(filePath);
        alzhimerdetectionsystem.AlzhimerDetectionSystem.main(filePath,"test");
           System.out.println("END File..");
      }
      catch(Exception ex)
      {
          System.err.println("Erro:  "+ ex);
      }
                           
                        }
                    }
                }
            }
        }
        
        try
        {
         ArrayList<String> Result = FeatureVectorComparision.main(null);
         for (int i = 0; i < Result.size(); i++) {
            String get = Result.get(i);
            jTextArea2.append(get);
            jTextArea2.append("\n");
        }
        }
        catch(Exception ex)
        {
            System.err.println("Exception :  "+ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
